---
title: "Tables"
author: "Bryan P. Galligan"
date: "5/28/2022"
output: pdf_document
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tables for FishTrapsFoodSec

```{r}

# Load packages
library(readr)
library(knitr)
library(plotrix)
library(kableExtra)

# Import data
TripData <- read_csv("04_DataExploration_Out/TripDataForAnalysis_GatedTraps_Galligan.csv")

# Subset by trap type
trad.trip <- subset(TripData, TripData$TrapType == "Traditional")
gated.trip <- subset(TripData, TripData$TrapType == "Gated")

# Table columns 
GatedTrapConcentration <- c(
  mean(gated.trip$CaConc_mgPer100g),
  mean(gated.trip$FeConc_mgPer100g),
  mean(gated.trip$Omega3Conc_gPer100g),
  mean(gated.trip$VAConc_ugPer100g),
  mean(gated.trip$SeConc_ugPer100g),
  mean(gated.trip$ZnConc_ugPer100g))

SE_GTC <- c(
  std.error(gated.trip$CaConc_mgPer100g),
  std.error(gated.trip$FeConc_mgPer100g),
  std.error(gated.trip$Omega3Conc_gPer100g),
  std.error(gated.trip$VAConc_ugPer100g),
  std.error(gated.trip$SeConc_ugPer100g),
  std.error(gated.trip$ZnConc_ugPer100g)
)

TraditionalTrapConcentration <- c(
  mean(trad.trip$CaConc_mgPer100g),
  mean(trad.trip$FeConc_mgPer100g),
  mean(trad.trip$Omega3Conc_gPer100g),
  mean(trad.trip$VAConc_ugPer100g),
  mean(trad.trip$SeConc_ugPer100g),
  mean(trad.trip$ZnConc_ugPer100g)
)

SE_TTC <- c(
  std.error(trad.trip$CaConc_mgPer100g),
  std.error(trad.trip$FeConc_mgPer100g),
  std.error(trad.trip$Omega3Conc_gPer100g),
  std.error(trad.trip$VAConc_ugPer100g),
  std.error(trad.trip$SeConc_ugPer100g),
  std.error(trad.trip$ZnConc_ugPer100g)
)

GatedTrapYield <- c(
  mean(gated.trip$CaPUE),
  mean(gated.trip$FePUE),
  mean(gated.trip$Omega3PUE),
  mean(gated.trip$VAPUE),
  mean(gated.trip$SePUE),
  mean(gated.trip$ZnPUE)
)

SE_GTY <- c(
  std.error(gated.trip$CaPUE),
  std.error(gated.trip$FePUE),
  std.error(gated.trip$Omega3PUE),
  std.error(gated.trip$VAPUE),
  std.error(gated.trip$SePUE),
  std.error(gated.trip$ZnPUE)
)

TraditionalTrapYield <- c(
  mean(trad.trip$CaPUE),
  mean(trad.trip$FePUE),
  mean(trad.trip$Omega3PUE),
  mean(trad.trip$VAPUE),
  mean(trad.trip$SePUE),
  mean(trad.trip$ZnPUE)
)

SE_TTY <- c(
  std.error(trad.trip$CaPUE),
  std.error(trad.trip$FePUE),
  std.error(trad.trip$Omega3PUE),
  std.error(trad.trip$VAPUE),
  std.error(trad.trip$SePUE),
  std.error(trad.trip$ZnPUE)
)

RDI <- c(700, 7, 0.7, 300, 20, 3)

# Make a data frame
tab1 <- data.frame(GatedTrapConcentration, SE_GTC, TraditionalTrapConcentration, SE_TTC, GatedTrapYield, SE_GTY, TraditionalTrapYield, SE_TTY, RDI)

# Row names
rownames(tab1) <- c("Calcium (mg)", "Iron (mg)", "Omega-3 (g)",
  paste("Vitamin A (", "\u00b5", "g)", sep = ""),
  paste("Selenium (", "\u00b5", "g)", sep = ""),
  "Zinc (mg)")

# Column names
colnames(tab1) <- c(
  "Gated Trap Concentration (100g^-1^)",
  "±SE",
  "Traditional Trap Concentration (100g^-1^)",
  "±SE",
  "Gated Trap Yield (Trap^-1^)",
  "±SE",
  "Traditional Trap Yield (Trap^-1^)",
  "±SE",
  "Recommended Daily Intake (Child 1-3 yrs)"
  )

# Render a table
kable(tab1, digits = 2)


```
